---
title: "Trabajo Final metodos supervisados"
format: pdf
editor: visual
---

```{r}
df <- read.csv("C:/Users/aaron/Desktop/USM/Analisis de Negocios/garments_worker_productivity.csv")
```

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(GGally)
library(MLmetrics)
library(lmtest)
library(car)
library(gsubfn)
library(readr)
library(tidyverse)
library(DataExplorer)
library(rsample)
library(parsnip)
library(recipes)
library(workflows)
library(yardstick)
library(caret)
library(tensorflow)
library(keras)
library(reticulate)
library(nnet)
library(parallel)
library(doParallel)
library(MASS)
library(rpart)
library(rpart.plot)
library(corrplot)
library(skimr)
library(neuralnet)
library(nnet)
library(keras)
```

```{r}
skim(df)
```

```{r}
encoded_df <- dummyVars(~ quarter + day + department, data = df) %>% predict(df)
df <- cbind(df[, !(names(df) %in% c("quarter", "day", "department"))], encoded_df)

```

```{r}
df <- df[, -which(names(df) == "date")]
```

```{r}
colSums(is.na(df))
```

```{r}
df[is.na(df)] <- 0
colSums(is.na(df))
```

```{r}
plot_intro(df)
```

```{r}
plot_histogram(df)
```

```{r}
plot_intro(df)

```

```{r}
plot_correlation(df)

```

```{r}
plot_histogram(df)

```

```{r}
df[is.na(df)] <- 0
colSums(is.na(df))
```

```{r}
# Generate box plots of all numeric variables
new_df_num <- data.frame(df$targeted_productivity,
                           df$team,
                           df$smv,
                           df$wip,
                           df$over_time,
                           df$incentive,
                           df$idle_time,
                           df$idle_men,
                           df$no_of_style_change,
                           df$no_of_workers,
                           df$actual_productivity)
col <- c("targeted_productivity", "standard_minute_value","team", 
         "work_in_progress", "over_time", "incentive", "idle_time", "idle_men", "no_of_style_change", 
         "no_of_workers", "actual_productivity")

colnames(new_df_num) <- col

ggplot(gather(new_df_num), aes(key,value)) +
  geom_boxplot(color="red", fill="yellow") +
  facet_wrap(~key, scales="free") +
  labs(title = "Box plots de la distribución de las variables no categoricas")
```

```{r}
split <- initial_split(df, prop = 0.8)
train_data <- training(split)
test_data <- testing(split)
```

```{r}
model_glm <- glm(actual_productivity~., data = train_data)
summary(model_glm)
probabilities <- model_glm %>% predict(test_data, type = "response")
predicted.classes <- ifelse(probabilities > 0.5, 1, 0)
```

```{r}
library(rpart)
tree_fit = rpart(actual_productivity~., data = train_data)
summary(tree_fit)
rpart.plot(tree_fit)
```
